baseURL = "https://example.com"
title = "Jennifer Cwagenberg"
theme = "m10c"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Jennifer Cwagenberg"
  description = "Nerdy things happen here."
  menu_item_separator = " - "
  avatar = "avatar.png"
  [[params.social]]
    name = "github"
    url = "https://github.com/candiedcode"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/candiedcode"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jennifercwagenberg/"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"